schema_version = "1.0.0"

id = "anachronox_md2"
version = "1.5.0"
name = "Anachronox MD2 Model Importer"
tagline = "Import Anachronox (Modified Quake II format) MD2 models into Blender"
maintainer = "GeneralProtectionFault"
type = "add-on"

blender_version_min = "4.2.0"
location = "File > Import > Anachronox (.md2)"

website = "https://github.com/GeneralProtectionFault/blender-anachronox-md2-importer"


license = [
  "GPL-3.0-or-later",
]

wheels = [
  "./wheels/pillow-12.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-win_amd64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-macosx_10_10_x86_64.whl"
]
